// Data Type: strings
//Concatenating strings

function concatenate_Sent() {
    var part_1 = "Hello, my name is "; //assigning a variable called part_1 the string value "Hello, my name is"
    var part_2 = " Vicky Jones.";
    var part_3 = "  Nice to meet you.";
    var whole_Sent = part_1.concat(part_2, part_3); //assigning a variable called "whole_Sent". The value of the variable uses the concatenate method. 
    // With the concatenate method you put the first variable, and then a .concat(). The brackets have the additional parts you want to concatenate. 

    document.getElementById("concatenate").innerHTML = whole_Sent;
}

// Slicing strings method

function slice_Method() {
    var Sentence = "Johnny is a very good boy";
    var Section = Sentence.slice(0, 6); // the first parameter within the slice method refer to the position of the first character that you want
    //taken out of the sentence and outputted. The first character has the position 0. The second parameter refers to where to end 
    //the extraction. It is the position, up to but NOT including where to end the extraction. 
    document.getElementById("slice").innerHTML = Section;
}

//to Uppercase method

function upper_Case() {
    var sentence = "Hello World";
    var output = sentence.toUpperCase(); //assigns the variable "output" the value of the sentence ("Hello World") with the toUpperCase method applied to it. 

    document.getElementById("upper_Case").innerHTML = output;
}

//search method

function search_Method() {
    var sent = "Those flowers are pretty";
    var result = sent.search("flower");

    document.getElementById("result").innerHTML = result; //gives the result 6
}

//Number Methods

// toString() Method

function num_to_string() {
    var num = 182;
    var ans = num.toString();

    document.getElementById("nums_to_string").innerHTML = ans;
}

//Precision Method

function precision_method() {
    var num = 1053621.12455;
    var ans = num.toPrecision(15); //the "15" indicates the length of the number that will be generated by this method. 
    document.getElementById("precision").innerHTML = ans;
}

//toFix() method 

function toFixed() {
    var X = 45.3254198;
    var output = X.toFixed(3); // the "3" refers to how many decimal points to be rounded to. 
    document.getElementById("tofixed").innerHTML = output;
}

//string valueOf() method

function myFunction() {
    var str = "Jump rope!";
    var res = str.valueOf();
    document.getElementById("demo").innerHTML = res;
}